### ISSUE TITLE
Empty Task Gets Added To The List

### ISSUE THREAD

**Issue by sk-faiz** [prajapatiomkar/Note-Taking-App#1]

**Comment by prajapatiomkar** [comment]
Ok we will work on it 👍

**Comment by sk-faiz** [comment]
Well I solved it already XD

**Comment by prajapatiomkar** [comment]
## Before 
```
if (item) {
    items.push(item)
    res.redirect("/")
}
```

## After 
```
if (item) {
    items.push(item)
    res.redirect("/")
}else{
    res.redirect("/")
}
```

## Explaination
When we checking if conditon we also to take care of else , else it show  ↩
![image](https://user-images.githubusercontent.com/72141037/187210409-e8865ff7-52e8-46e2-b548-02118ba67c13.png)

**Comment by prajapatiomkar** [comment]
Thanks for rectifying, I Fixed the issue😎.
